version: "3.9"
services:
  ecw-to-tiff:
    build: ./app
    volumes:
      - "${UPLOAD_FOLDER_MOUNT_PATH}:/ecw-to-tiff/uploads"
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      - "${DOCKER_LIB}:/usr/local/bin/docker"
    ports: 
      - 8888:8888
    env_file:
      - .env
