version: "3.9"
services:
  ecw-to-tiff:
    build: ./app
    volumes:
      - "./app:/ecw-to-tiff/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/local/bin/docker"
    ports: 
      - 8888:8888
    env_file:
      - ./app/.env
